/*

Boost Software License - Version 1.0 - August 17th,2003

Permission is hereby granted,free of charge,to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use,reproduce,display,distribute,
execute,and transmit the Software,and to prepare derivative works of the
Software,and to permit third-parties to whom the Software is furnished to
do so,all subject to the following:

The copyright notices in the Software and this entire statement,including
the above license grant,this restriction and the following disclaimer,
must be included in all copies of the Software,in whole or in part,and
all derivative works of the Software,unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND,EXPRESS OR
IMPLIED,INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE,TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE,
ARISING FROM,OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module derelict.pq.types;

alias Oid = uint;
alias pqbool = char;
alias pg_int64 = long;
public import core.stdc.stdio : FILE;

enum {
    PG_COPYRES_ATTRS       = 0x01,
    PG_COPYRES_TUPLES      = 0x02,
    PG_COPYRES_EVENTS      = 0x04,
    PG_COPYRES_NOTICEHOOKS = 0x08,
}

alias ConnStatusType = int;
enum {
    CONNECTION_OK,
    CONNECTION_BAD,
    CONNECTION_STARTED,
    CONNECTION_MADE,
    CONNECTION_AWAITING_RESPONSE,
    CONNECTION_AUTH_OK,
    CONNECTION_SETENV,
    CONNECTION_SSL_STARTUP,
    CONNECTION_NEEDED
}

alias PostgresPollingStatusType = int;
enum {
    PGRES_POLLING_FAILED = 0,
    PGRES_POLLING_READING,
    PGRES_POLLING_WRITING,
    PGRES_POLLING_OK,
    PGRES_POLLING_ACTIVE
}

alias ExecStatusType = int;
enum {
    PGRES_EMPTY_QUERY = 0,
    PGRES_COMMAND_OK,
    PGRES_TUPLES_OK,
    PGRES_COPY_OUT,
    PGRES_COPY_IN,
    PGRES_BAD_RESPONSE,
    PGRES_NONFATAL_ERROR,
    PGRES_FATAL_ERROR,
    PGRES_COPY_BOTH,
    PGRES_SINGLE_TUPLE
}

alias PGTransactionStatusType = int;
enum {
    PQTRANS_IDLE,
    PQTRANS_ACTIVE,
    PQTRANS_INTRANS,
    PQTRANS_INERROR,
    PQTRANS_UNKNOWN
}

alias PGVerbosity = int;
enum {
    PQERRORS_TERSE,
    PQERRORS_DEFAULT,
    PQERRORS_VERBOSE
}

alias PGContextVisibility = int;
enum{
    PQSHOW_CONTEXT_NEVER,
    PQSHOW_CONTEXT_ERRORS,
    PQSHOW_CONTEXT_ALWAYS
} ;

alias PGPing = int;
enum {
    PQPING_OK,
    PQPING_REJECT,
    PQPING_NO_RESPONSE,
    PQPING_NO_ATTEMTP
}

struct PGconn;
struct PGresult;
struct PGcancel;

struct PGnotify {
    char* relname;
    int be_pid;
    char* extra;
    private PGnotify* next;
}

extern(C) @nogc nothrow {
    alias PQnoticeReceiver = void function(void*,PGresult*);
    alias PQnoticeProcessor = void function(void*,char*);
}

struct PQprintOpt {
    pqbool header;
    pqbool aligment;
    pqbool standard;
    pqbool html3;
    pqbool expander;
    pqbool pager;
    char* fieldSep;
    char* tableOpt;
    char* caption;
    char** fieldName;
}

struct PQconninfoOption {
    char* keyword;
    char* envvar;
    char* compiled;
    char* val;
    char* label;
    char* dispchar;
    int dispsize;
}

struct PQArgBlock {
    int len;
    int ising;
    union u
    {
        int* ptr;
        int integer;
    }
}

struct PGresAttDesc {
    char* name;
    Oid tableid;
    int columnid;
    int format;
    Oid typid;
    int typlen;
    int atttypmod;
}

alias PGEventId = int;
enum {
    PGEVT_REGISTER,
    PGEVT_CONNRESET,
    PGEVT_CONNDESTROY,
    PGEVT_RESULTCREATE,
    PGEVT_RESULTCOPY,
    PGEVT_RESULTDESTROY
}

struct PGEventResultCreate {
    PGconn* conn;
    PGresult* result;
}

extern(C) @nogc nothrow {
    alias pgthreadlock_t = void function(int);
    alias PGEventProc = size_t function(PGEventId,void*,void*);
}

// from postgres_ext.h
enum : int {
    PG_DIAG_SEVERITY =          'S',
    PG_DIAG_SEVERITY_NONLOCALIZED = 'V', // New in 9.6
    PG_DIAG_SQLSTATE =          'C',
    PG_DIAG_MESSAGE_PRIMARY =   'M',
    PG_DIAG_MESSAGE_DETAIL =    'D',
    PG_DIAG_MESSAGE_HINT =      'H',
    PG_DIAG_STATEMENT_POSITION ='P',
    PG_DIAG_INTERNAL_POSITION = 'p',
    PG_DIAG_INTERNAL_QUERY =    'q',
    PG_DIAG_CONTEXT =           'W',
    PG_DIAG_SCHEMA_NAME =       's',
    PG_DIAG_TABLE_NAME =        't',
    PG_DIAG_COLUMN_NAME =       'c',
    PG_DIAG_DATATYPE_NAME =     'd',
    PG_DIAG_CONSTRAINT_NAME =   'n',
    PG_DIAG_SOURCE_FILE =       'F',
    PG_DIAG_SOURCE_LINE =       'L',
    PG_DIAG_SOURCE_FUNCTION =   'R'
}